/* 
 * Project Euler - Problem 12
 * Highly Divisible Triangular Number
 *
 * The sequence of triangle numbers is generated by adding 
 * the natural numbers. So the 7th triangle number would be
 * 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. 
 * The first ten terms would be:
 * 
 * 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
 * 
 * Let us list the factors of the first seven triangle numbers:
 * 
 *  1: 1
 *  3: 1,3
 *  6: 1,2,3,6
 * 10: 1,2,5,10
 * 15: 1,3,5,15
 * 21: 1,3,7,21
 * 28: 1,2,4,7,14,28
 * We can see that 28 is the first triangle number to have over
 * five divisors.
 * 
 * What is the value of the first triangle number to have over
 * five hundred divisors?
 *
 */

#include <stdio.h>
#include <math.h>

// Brute Force Method

/* NumberOfDivisors
 * quick way of finding all divisors
 *
 * This works by taking the sqare root of the number and
 * dividing the original number by all values between 1
 * and the rooted number
 * 
 */
int NumberOfDivisors(int number) {

    int nod = 0; // number of divisors
    int num = (int) sqrt(number);
 
    for(int i = 1; i<= num; i++){
        if(number % i == 0){
            nod += 2;
        }
    }
    //Correction if the number is a perfect square
    if (num * num == number) {
        nod--;
    }
 
    return nod;
}

/** MAIN **/
int main(int argc, char const *argv[])
{
	int number = 0;
    int i = 1;
     
    while(NumberOfDivisors(number) < 500){
        number += i;
        i++;
    }

    printf("This answer is: %d\n",number);
	return 0;
}